version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sims_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app.py:/app/app.py
      - ./backend/migrations:/app/migrations
      - ./backend/.env:/app/.env:ro
      - sims_data:/app/instance
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sims_network

  frontend:
    build: ./frontend
    container_name: sims_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - sims_network

networks:
  sims_network:
    driver: bridge

volumes:
  sims_data:
    driver: local 