"""Add image, favicon, score, extras, full_text, summary_json to Article

Revision ID: 651bc5ed60f4
Revises: 80a8184de433
Create Date: 2025-05-23 01:02:50.145313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651bc5ed60f4'
down_revision = '80a8184de433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('favicon', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('extras', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('full_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('summary_json')
        batch_op.drop_column('full_text')
        batch_op.drop_column('extras')
        batch_op.drop_column('score')
        batch_op.drop_column('favicon')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
